frr defaults datacenter
hostname spine
service integrated-vtysh-config
!
interface eth1
 ip address 10.0.1.2/30
exit
!
interface eth2
 ip address 10.0.2.2/30
exit
!
interface lo
 ip address 10.255.0.254/32
exit
!
router bgp 65000
 bgp router-id 10.255.0.254
 bgp cluster-id 10.0.0.254
 no bgp default ipv4-unicast
 neighbor 10.0.1.1 remote-as 65000
 neighbor 10.0.2.1 remote-as 65000
 !
 address-family ipv4 unicast
  neighbor 10.0.1.1 activate
  neighbor 10.0.1.1 route-reflector-client
  neighbor 10.0.1.1 next-hop-self force
  neighbor 10.0.2.1 activate
  neighbor 10.0.2.1 route-reflector-client
  neighbor 10.0.2.1 next-hop-self force
 exit-address-family
 !
 address-family l2vpn evpn
  neighbor 10.0.1.1 activate
  neighbor 10.0.1.1 route-reflector-client
  neighbor 10.0.2.1 activate
  neighbor 10.0.2.1 route-reflector-client
 exit-address-family
!
