frr version 10.7.0
frr defaults traditional
hostname r1

interface eth1
 ipv6 address 2001:db8:1::1/64
exit

interface rtr 
 ipv6 address 2001:db8:12::1/64
exit

ipv6 route 2001:db8:2::/64 2001:db8:12::2

line vty
