frr defaults traditional
hostname rr2
!
router bgp 65000
 bgp router-id 3.3.3.3
 no bgp default ipv4-unicast
 neighbor 192.0.2.5 remote-as 65000
 neighbor 192.0.2.10 remote-as 65000
 !
 address-family ipv4 labeled-unicast
  neighbor 192.0.2.5 activate
  neighbor 192.0.2.5 route-reflector-client
  neighbor 192.0.2.5 next-hop-self force
  neighbor 192.0.2.10 activate
  neighbor 192.0.2.10 route-reflector-client
  neighbor 192.0.2.10 next-hop-self force
  network 3.3.3.3/32
 exit-address-family
!
interface lo
 ip address 3.3.3.3/32
!
interface eth1
 ip address 192.0.2.6/30
 mpls enable
!
interface eth2
 ip address 192.0.2.9/30
 mpls enable
!
