frr version 10.7.0
frr defaults traditional
hostname pe2
!
router bgp 65000
 bgp router-id 10.0.0.22
 neighbor 10.0.1.2 remote-as 65000
 neighbor 10.0.20.1 remote-as 65200
 !
 address-family ipv4 unicast
  neighbor 10.0.1.2 activate
  neighbor 10.0.1.2 next-hop-self
  neighbor 10.0.20.1 activate
  network 10.0.0.22/32
 exit-address-family
!

line vty
