frr version 10.7.0
frr defaults traditional
hostname pe2
!
ip prefix-list CE2-LO seq 10 permit 10.2.2.2/32
!
route-map CE2-LO-RM-IN permit 10
 match ip address prefix-list CE2-LO
exit
!
router bgp 65000
 bgp router-id 10.0.0.22
 neighbor 10.0.1.2 remote-as 65000
 neighbor 10.0.20.1 remote-as 65200
 !
 address-family ipv4 unicast
  network 10.0.0.22/32
  neighbor 10.0.1.2 activate
  ! Overwrite next-hop when advertising to ibgp fabric since we are CE-facing PE.
  neighbor 10.0.1.2 next-hop-self
  neighbor 10.0.20.1 activate
  neighbor 10.0.20.1 route-map CE2-LO-RM-IN in
 exit-address-family
!

line vty
