frr version 10.7.0
frr defaults traditional
hostname r2

interface rtr
 ipv6 address 2001:db8:12::2/64
exit

interface eth1
 ipv6 address 2001:db8:2::1/64
exit

ipv6 route 2001:db8:1::/64 2001:db8:12::1

line vty
