frr version 10.7.0
frr defaults traditional
hostname ce1
!
ip prefix-list CE1-LO seq 10 permit 10.1.1.1/32
!
route-map CE1-LO-RM-OUT permit 10
 match ip address prefix-list CE1-LO
exit
!
router bgp 65100
 bgp router-id 10.1.1.1
 neighbor 10.0.10.0 remote-as 65000
 !
 address-family ipv4 unicast
  network 10.1.1.1/32
  neighbor 10.0.10.0 activate
  neighbor 10.0.10.0 route-map CE1-LO-RM-OUT out
 exit-address-family
!

line vty
