frr defaults traditional
hostname pe1
!
router bgp 65000
 bgp router-id 1.1.1.1
 no bgp default ipv4-unicast
 neighbor 192.0.2.2 remote-as 65000
 neighbor 192.0.2.2 update-source eth1
 neighbor 4.4.4.4 remote-as 65000
 neighbor 4.4.4.4 update-source lo
 !
 address-family ipv4 labeled-unicast
  neighbor 192.0.2.2 activate
  network 1.1.1.1/32
  redistribute connected
 exit-address-family
 !
 address-family ipv4 vpn 
  neighbor 4.4.4.4 activate
 exit-address-family
!
router bgp 65000 vrf red
 address-family ipv4 unicast
  redistribute connected
  label vpn export auto
  rd vpn export 65000:100
  rt vpn both 65000:100
  export vpn
  import vpn
 exit-address-family
router bgp 65000 vrf green
 address-family ipv4 unicast
  redistribute connected
  label vpn export auto
  rd vpn export 65000:101
  rt vpn both 65000:101
  export vpn
  import vpn
 exit-address-family
router bgp 65000 vrf blue
 address-family ipv4 unicast
  redistribute connected
  label vpn export auto
  rd vpn export 65000:102
  rt vpn both 65000:102
  export vpn
  import vpn
 exit-address-family
!
interface lo
 ip address 1.1.1.1/32
!
interface eth1
 ip address 192.0.2.1/30
 mpls enable
!
interface eth3
 ip address 10.1.0.1/24
!
interface eth4
 ip address 10.2.0.1/24
!
interface eth5
 ip address 10.3.0.1/24
!
